### ISSUE TITLE
Como trabalhar com as variáveis de ambiente host e key do ckan

### ISSUE THREAD

**Issue by gabrielbdornas** [dados-mg/dpckan#24]
Premissas:
- Utilizar o pacote para publicação/atualização de recursos em qualquer instância CKAN
- Não utilizar nomes padrões vinculadas a ambientes (produção, homologação, por exemplo) tendo em vista que cada usuário poderá definir o seu ambiente
- Possibilidade de utilização para multiplos ambientes
- Facilitar a chamada das funções, determinando nomes padrões, dando a possibilidade de configurações adicionais para modificação do padrão

Solução proposta:
- Cadastro de variáveis de ambiente na máquina, padrões:
  - CKAN_HOST: endereço (sem http:// ou https.//)
  - CKAN_KEY: chave ckan para autorizar as ações
- Por padrão funções buscarão estas variáveis
- Necessário utilizar outras instâncias criar outras variáveis (obrigatoriamente duas, uma para host e outra para key) incluir uma "flag" após no nome padrão. Exemplo: HOMOLOGA para CKAN_HOST_HOMOLOGA e CKAN_KEY_HOMOLOGA
- Nomes de variáveis que sairem do padrão CKAN_HOST e CKAN_KEY não serão aceitas   

Exemplos práticos
```
$ dpckan publish

# busca CKAN_HOST e CKAN_KEY (padrões) para publicação do dataset
```

```
$ dpckan publish -e HOMOLOGACAO

# busca CKAN_HOST_HOMOLOGACAO e CKAN_KEY_HOMOLOGACAO para publicação do dataset
```

```
$ dpckan publish --env TESTE

# busca CKAN_HOST_TESTE e CKAN_KEY_TESTE para publicação do dataset
```

```
$ dpckan publish -e staging

# busca CKAN_HOST_STAGING e CKAN_KEY_STAGING para publicação do dataset
```

**Comment by gabrielbdornas** [comment]
Issue será fechado pois tinha como objetivo apenas complementar #23

**Comment by fjuniorr** [comment]
Agora que eu consegui entender a proposta do pacote `dotenv`. Ótima descoberta @gabrielbdornas !!

O que você acha da gente combinar ela com a funcionalidade de [Values from Environment Variables](https://click.palletsprojects.com/en/8.0.x/options/#values-from-environment-variables) do click? Ficaria algo assim. 

Em cada subcomando que precisar do host e chave a gente coloca

```python
import click

@click.command(name='publish')
@click.option('--host', '-H', envvar='CKAN_HOST', required=True) # -H para respeitar convenção de -h ser help
@click.option('--key', '-k', envvar='CKAN_KEY', required=True)
def publish(host, key):
  """
  click.echo(host) # se precisarmos acessar diretamente a variável de ambiente usamos os.getenv('CKAN_HOST')
  click.echo(key)
```

Fazendo a inicialização do `dotenv` dentro do `dpckan/__init__.py` com:

```python
from dotenv import load_dotenv

load_dotenv()
```

A gente não precisa mais de `get_ckan_informations` e o usuário passa a escolher a forma mais conveniente de passar a informação

- argumento na linha de comando (eg. `dpckan publish --host http://dados.mg.gov.br/ --key ec5c0860-9e48-41f3-8850-4a7128b18df8`)
- variáveis de ambiente definidas via ambiente
- arquivo `.env` com variáveis de ambiente na pasta do projeto

Com isso a gente consegue suportar qualquer necessidade de publicar para ambientes diferentes no mesmo computador. Esse trecho da documentação que fez o clique pra mim

> If your application takes its configuration from environment variables, like a 12-factor
application, launching it in development is not very practical because you have to set
those environment variables yourself.
> 
> To help you with that, you can add Python-dotenv to your application to make it load the
configuration from a `.env` file when it is present (e.g. in development) while remaining
configurable via the environment:
> 
> ```python
> from dotenv import load_dotenv
> 
> load_dotenv()  # take environment variables from .env.
> 
> # Code of your application, which uses environment variables (e.g. from `os.environ` or
> # `os.getenv`) as if they came from the actual environment.
> ```
> 
> By default, `load_dotenv` doesn't override existing environment variables.

**Comment by gabrielbdornas** [comment]
@fjuniorr Perfeito! Acho que ficou melhor assim mesmo! Vou implementar aqui para testarmos.

**Comment by gabrielbdornas** [comment]
fechado com merge #31
